import {Laborer} from './laborer';

const defaultLaborers = [
  {
    id: '1',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john.doe@laborer.com',
    hireDate: new Date('2023-01-15'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'user',
  },
  {
    id: '2',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane.smith@laborer.com',
    hireDate: new Date('2023-02-20'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'admin',
  },
  {
    id: '3',
    firstName: 'Emily',
    lastName: 'Jones',
    email: 'emily.jones@laborer.com',
    hireDate: new Date('2023-03-10'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'user',
  },
  {
    id: '4',
    firstName: 'Michael',
    lastName: 'Brown',
    email: 'michael.brown@laborer.com',
    hireDate: new Date('2023-04-25'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'supervisor',
  },
  {
    id: '5',
    firstName: 'Linda',
    lastName: 'Wilson',
    email: 'linda.wilson@laborer.com',
    hireDate: new Date('2023-05-30'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'admin',
  },
  {
    id: '6',
    firstName: 'David',
    lastName: 'Johnson',
    email: 'david.johnson@laborer.com',
    hireDate: new Date('2023-06-15'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'user',
  },
  {
    id: '7',
    firstName: 'Sarah',
    lastName: 'Anderson',
    email: 'sarah.anderson@laborer.com',
    hireDate: new Date('2023-07-20'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'admin',
  },
  {
    id: '8',
    firstName: 'Daniel',
    lastName: 'Martinez',
    email: 'daniel.martinez@laborer.com',
    hireDate: new Date('2023-08-10'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'user',
  },
  {
    id: '9',
    firstName: 'Jessica',
    lastName: 'Taylor',
    email: 'jessica.taylor@laborer.com',
    hireDate: new Date('2023-09-25'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'supervisor',
  },
  {
    id: '10',
    firstName: 'Matthew',
    lastName: 'Walker',
    email: 'matthew.walker@laborer.com',
    hireDate: new Date('2023-10-30'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'admin',
  },
  {
    id: '11',
    firstName: 'Alex',
    lastName: 'Wilson',
    email: 'alex.wilson@laborer.com',
    hireDate: new Date('2023-11-15'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'user',
  },
  {
    id: '12',
    firstName: 'Olivia',
    lastName: 'Davis',
    email: 'olivia.davis@laborer.com',
    hireDate: new Date('2023-12-20'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'admin',
  },
  {
    id: '13',
    firstName: 'Robert',
    lastName: 'Johnson',
    email: 'robert.johnson@laborer.com',
    hireDate: new Date('2023-01-05'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'user',
  },
  {
    id: '14',
    firstName: 'Sophia',
    lastName: 'Brown',
    email: 'sophia.brown@laborer.com',
    hireDate: new Date('2023-02-10'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'admin',
  },
  {
    id: '15',
    firstName: 'William',
    lastName: 'Smith',
    email: 'william.smith@laborer.com',
    hireDate: new Date('2023-03-25'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'user',
  },
  {
    id: '16',
    firstName: 'Ava',
    lastName: 'Johnson',
    email: 'ava.johnson@laborer.com',
    hireDate: new Date('2023-04-30'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'supervisor',
  },
  {
    id: '17',
    firstName: 'James',
    lastName: 'Wilson',
    email: 'james.wilson@laborer.com',
    hireDate: new Date('2023-05-15'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'admin',
  },
  {
    id: '18',
    firstName: 'Mia',
    lastName: 'Davis',
    email: 'mia.davis@laborer.com',
    hireDate: new Date('2023-06-20'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'user',
  },
  {
    id: '19',
    firstName: 'Benjamin',
    lastName: 'Anderson',
    email: 'benjamin.anderson@laborer.com',
    hireDate: new Date('2023-07-10'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'admin',
  },
  {
    id: '20',
    firstName: 'Charlotte',
    lastName: 'Martinez',
    email: 'charlotte.martinez@laborer.com',
    hireDate: new Date('2023-08-25'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'user',
  },
  {
    id: '21',
    firstName: 'Henry',
    lastName: 'Taylor',
    email: 'henry.taylor@laborer.com',
    hireDate: new Date('2023-09-30'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'supervisor',
  },
  {
    id: '22',
    firstName: 'Amelia',
    lastName: 'Walker',
    email: 'amelia.walker@laborer.com',
    hireDate: new Date('2023-10-15'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'admin',
  },
  {
    id: '23',
    firstName: 'Daniel',
    lastName: 'Wilson',
    email: 'daniel.wilson@laborer.com',
    hireDate: new Date('2023-11-20'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'user',
  },
  {
    id: '24',
    firstName: 'Evelyn',
    lastName: 'Davis',
    email: 'evelyn.davis@laborer.com',
    hireDate: new Date('2023-12-10'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'admin',
  },
  {
    id: '25',
    firstName: 'Oliver',
    lastName: 'Johnson',
    email: 'oliver.johnson@laborer.com',
    hireDate: new Date('2023-01-01'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'user',
  },
  {
    id: '26',
    firstName: 'Sophie',
    lastName: 'Brown',
    email: 'sophie.brown@laborer.com',
    hireDate: new Date('2023-02-05'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'admin',
  },
  {
    id: '27',
    firstName: 'Noah',
    lastName: 'Smith',
    email: 'noah.smith@laborer.com',
    hireDate: new Date('2023-03-20'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'user',
  },
  {
    id: '28',
    firstName: 'Emma',
    lastName: 'Johnson',
    email: 'emma.johnson@laborer.com',
    hireDate: new Date('2023-04-15'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'supervisor',
  },
  {
    id: '29',
    firstName: 'Liam',
    lastName: 'Wilson',
    email: 'liam.wilson@laborer.com',
    hireDate: new Date('2023-05-10'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'admin',
  },
  {
    id: '30',
    firstName: 'Olivia',
    lastName: 'Davis',
    email: 'olivia.davis@laborer.com',
    hireDate: new Date('2023-06-25'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'user',
  },
  {
    id: '31',
    firstName: 'Lucas',
    lastName: 'Anderson',
    email: 'lucas.anderson@laborer.com',
    hireDate: new Date('2023-07-20'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'admin',
  },
  {
    id: '32',
    firstName: 'Ava',
    lastName: 'Martinez',
    email: 'ava.martinez@laborer.com',
    hireDate: new Date('2023-08-15'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'user',
  },
  {
    id: '33',
    firstName: 'Mason',
    lastName: 'Taylor',
    email: 'mason.taylor@laborer.com',
    hireDate: new Date('2023-09-10'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'supervisor',
  },
  {
    id: '34',
    firstName: 'Isabella',
    lastName: 'Walker',
    email: 'isabella.walker@laborer.com',
    hireDate: new Date('2023-10-05'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'admin',
  },
  {
    id: '35',
    firstName: 'Ethan',
    lastName: 'Wilson',
    email: 'ethan.wilson@laborer.com',
    hireDate: new Date('2020-11-30'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'user',
  },
  {
    id: '36',
    firstName: 'Mia',
    lastName: 'Davis',
    email: 'mia.davis@laborer.com',
    hireDate: new Date('2023-12-25'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'admin',
  },
  {
    id: '37',
    firstName: 'Elijah',
    lastName: 'Johnson',
    email: 'elijah.johnson@laborer.com',
    hireDate: new Date('2021-01-10'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'user',
  },
  {
    id: '38',
    firstName: 'Scarlett',
    lastName: 'Brown',
    email: 'scarlett.brown@laborer.com',
    hireDate: new Date('2020-02-15'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'admin',
  },
  {
    id: '39',
    firstName: 'Logan',
    lastName: 'Smith',
    email: 'logan.smith@laborer.com',
    hireDate: new Date('2013-03-20'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'user',
  },
  {
    id: '40',
    firstName: 'Avery',
    lastName: 'Johnson',
    email: 'avery.johnson@laborer.com',
    hireDate: new Date('2023-04-25'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'supervisor',
  },
  {
    id: '41',
    firstName: 'Ella',
    lastName: 'Wilson',
    email: 'ella.wilson@laborer.com',
    hireDate: new Date('2020-05-30'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'admin',
  },
  {
    id: '42',
    firstName: 'Jackson',
    lastName: 'Davis',
    email: 'jackson.davis@laborer.com',
    hireDate: new Date('2023-06-15'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'user',
  },
  {
    id: '43',
    firstName: 'Penelope',
    lastName: 'Anderson',
    email: 'penelope.anderson@laborer.com',
    hireDate: new Date('2023-07-20'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'admin',
  },
  {
    id: '44',
    firstName: 'Leo',
    lastName: 'Martinez',
    email: 'leo.martinez@laborer.com',
    hireDate: new Date('2020-08-10'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'user',
  },
  {
    id: '45',
    firstName: 'Stella',
    lastName: 'Taylor',
    email: 'stella.taylor@laborer.com',
    hireDate: new Date('2023-09-25'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'supervisor',
  },
  {
    id: '46',
    firstName: 'Lucas',
    lastName: 'Brown',
    email: 'lucas.brown@laborer.com',
    hireDate: new Date('2023-10-30'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'admin',
  },
  {
    id: '47',
    firstName: 'Harper',
    lastName: 'Johnson',
    email: 'harper.johnson@laborer.com',
    hireDate: new Date('2018-11-15'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'user',
  },
  {
    id: '48',
    firstName: 'Jackson',
    lastName: 'Davis',
    email: 'jackson.davis@laborer.com',
    hireDate: new Date('2023-12-20'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'admin',
  },
  {
    id: '49',
    firstName: 'Emma',
    lastName: 'Wilson',
    email: 'emma.wilson@laborer.com',
    hireDate: new Date('2019-01-05'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'user',
  },
  {
    id: '50',
    firstName: 'Liam',
    lastName: 'Davis',
    email: 'liam.davis@laborer.com',
    hireDate: new Date('2024-02-10'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'admin',
  },
  {
    id: '51',
    firstName: 'Olivia',
    lastName: 'Johnson',
    email: 'olivia.johnson@laborer.com',
    hireDate: new Date('2024-03-15'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'user',
  },
  {
    id: '52',
    firstName: 'Ethan',
    lastName: 'Brown',
    email: 'ethan.brown@laborer.com',
    hireDate: new Date('2024-04-20'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'admin',
  },
  {
    id: '53',
    firstName: 'Ava',
    lastName: 'Wilson',
    email: 'ava.wilson@laborer.com',
    hireDate: new Date('2024-05-10'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'user',
  },
  {
    id: '54',
    firstName: 'Mason',
    lastName: 'Davis',
    email: 'mason.davis@laborer.com',
    hireDate: new Date('2024-06-25'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'supervisor',
  },
  {
    id: '55',
    firstName: 'Isabella',
    lastName: 'Johnson',
    email: 'isabella.johnson@laborer.com',
    hireDate: new Date('2024-07-20'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'admin',
  },
  {
    id: '56',
    firstName: 'James',
    lastName: 'Brown',
    email: 'james.brown@laborer.com',
    hireDate: new Date('2024-08-15'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'user',
  },
  {
    id: '57',
    firstName: 'Emily',
    lastName: 'Wilson',
    email: 'emily.wilson@laborer.com',
    hireDate: new Date('2020-09-10'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'admin',
  },
  {
    id: '58',
    firstName: 'Benjamin',
    lastName: 'Davis',
    email: 'benjamin.davis@laborer.com',
    hireDate: new Date('2021-10-05'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'user',
  },
  {
    id: '59',
    firstName: 'Charlotte',
    lastName: 'Johnson',
    email: 'charlotte.johnson@laborer.com',
    hireDate: new Date('2022-11-30'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'supervisor',
  },
  {
    id: '60',
    firstName: 'Henry',
    lastName: 'Brown',
    email: 'henry.brown@laborer.com',
    hireDate: new Date('2023-12-25'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'admin',
  },
  {
    id: '61',
    firstName: 'Sophia',
    lastName: 'Johnson',
    email: 'sophia.johnson@laborer.com',
    hireDate: new Date('2021-01-01'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'user',
  },
  {
    id: '62',
    firstName: 'William',
    lastName: 'Davis',
    email: 'william.davis@laborer.com',
    hireDate: new Date('2021-02-05'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'admin',
  },
  {
    id: '63',
    firstName: 'Olivia',
    lastName: 'Wilson',
    email: 'olivia.wilson@laborer.com',
    hireDate: new Date('2021-03-10'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'user',
  },
  {
    id: '64',
    firstName: 'Liam',
    lastName: 'Brown',
    email: 'liam.brown@laborer.com',
    hireDate: new Date('2021-04-15'),
    picture: '/backend/src/assets/laborer2.png',
    role: 'supervisor',
  },
  {
    id: '65',
    firstName: 'Emma',
    lastName: 'Davis',
    email: 'emma.davis@laborer.com',
    hireDate: new Date('2021-05-20'),
    picture: '/backend/src/assets/laborer1.jpg',
    role: 'admin',
  }
];

const initializeLaborers = async () => {
    try {
      await Laborer.bulkCreate(defaultLaborers, { ignoreDuplicates: true });
    } catch (error) {
      console.error('Error initializing laborers:', error);
    }
  };
  
  export default initializeLaborers;